### ISSUE TITLE
SparkNet for CPU-only clusters

### ISSUE THREAD

**Issue by ravi9** [amplab/SparkNet#110]
Could you provide SparkNet for CPU-only clusters ?

**Comment by robertnishihara** [comment]
Hi Ravi, we built some jars without CUDA. It should work if you try changing the relevant lines in `build.sbt` to

```
resolvers += "javacpp" at "http://www.eecs.berkeley.edu/~rkn/snapshot-2016-03-16-CPU/"

libraryDependencies += "org.bytedeco" % "javacpp" % "1.2-SPARKNETCPU"

libraryDependencies += "org.bytedeco.javacpp-presets" % "caffe" % "master-1.2-SPARKNETCPU"

libraryDependencies += "org.bytedeco.javacpp-presets" % "caffe" % "master-1.2-SPARKNETCPU" classifier "linux-x86_64"

libraryDependencies += "org.bytedeco.javacpp-presets" % "opencv" % "3.1.0-1.2-SPARKNETCPU"

libraryDependencies += "org.bytedeco.javacpp-presets" % "opencv" % "3.1.0-1.2-SPARKNETCPU" classifier "linux-x86_64"

libraryDependencies += "org.bytedeco.javacpp-presets" % "tensorflow" % "master-1.2-SPARKNETCPU"

libraryDependencies += "org.bytedeco.javacpp-presets" % "tensorflow" % "master-1.2-SPARKNETCPU" classifier "linux-x86_64"
```

Basically, change the URL to **snapshot-2016-03-16-CPU** and change all of the instances of SPARKNET to SPARKNETCPU.

**Comment by ravi9** [comment]
Great! Thanks. I will try it out.

**Comment by robertnishihara** [comment]
Closing because this is addressed. Please reopen if you encounter a problem.

**Comment by ravi9** [comment]
Sure, thanks.

**Comment by javadba** [comment]
Is the March 16 snapshot still the best way to get cpu only?

**Comment by robertnishihara** [comment]
Yes, it is.

**Comment by skmishra5** [comment]
Hi,

I am also trying to build for CPU only clusters. I changed the URL to snapshot-2016-03-16-CPU and change all of the instances of SPARKNET to SPARKNETCPU as instructed above. But it still gives me the below error.

[error] (*:update) sbt.ResolveException: unresolved dependency: org.bytedeco#javacpp;1.2-SPARKNETCPU: not found
[error] unresolved dependency: org.bytedeco.javacpp-presets#caffe;master-1.2-SPARKNETCPU: not found
[error] unresolved dependency: org.bytedeco.javacpp-presets#opencv;3.1.0-1.2-SPARKNETCPU: not found
[error] unresolved dependency: org.bytedeco.javacpp-presets#tensorflow;master-1.2-SPARKNETCPU: not found

Kindly help me with this.

Thanks and Regards,
Sitakanta Mishra

**Comment by rawar-zz** [comment]
+1
