### ISSUE TITLE
Hyperparameters optimizzation

### ISSUE THREAD

**Issue by bhack** [amplab/SparkNet#111]
Do you plan to add something similar to https://github.com/maxpumperla/hyperas?

**Comment by robertnishihara** [comment]
Hyperparameter optimization is a sensible way to use a cluster, so it's worth supporting well. Currently, if people load a model in SparkNet from a Caffe `.caffemodel` or a TensorFlow `.pb` file, then the net architecture will already be specified in the model file. Hyperparameter optimization  becomes easier if the users specify the models in Scala, but that seems like a less common use case.

**Comment by bhack** [comment]
Yes but there are also some emerging approach that pass the boundaries concept of hyperparameters search like what we started to discuss at https://github.com/maxpumperla/hyperas/issues/10
