### ISSUE TITLE
sbt assembly error

### ISSUE THREAD

**Issue by abongLee** [amplab/SparkNet#122]
[error] Could not run test TensorFlowNetSpec: java.util.NoSuchElementException: key not found: SPARKNET_HOME
...
...
...
[error] Could not run test CaffeNetSpec: java.util.NoSuchElementException: key not found: SPARKNET_HOME
[info] Run completed in 9 seconds, 564 milliseconds.
[info] Total number of tests run: 6
[info] Suites: completed 4, aborted 0
[info] Tests: succeeded 6, failed 0, canceled 0, ignored 1, pending 0
[info] All tests passed.
[error] Error during tests:
[error] 	TensorFlowNetSpec
[error] 	CaffeNetSpec
16/04/22 10:37:22 INFO RemoteActorRefProvider$RemotingTerminator: Remoting shut down.
[error] (test:test) sbt.TestsFailedException: Tests unsuccessful
[error] Total time: 133 s, completed 2016-4-22 10:37:22

I got the errors shown above when running sbt assembly . and I have set the variable
SPARKNET_HOME in the ~/.bashrc . I don't know why this happened . 

Any help would be greatly appreciated . Thanks

**Comment by robertnishihara** [comment]
If you already set `SPARKNET_HOME` in the `~/.bashrc`, can you try running `source ~/.bashrc` before compiling?

Or try running `export SPARKNET_HOME=/path/to/SparkNet` with the appropriate path?

**Comment by abongLee** [comment]
Yes ,  I do run source ~/.bashrc
and I verify that by 
echo $SPARKNET_HOME 
It works well.

**Comment by robertnishihara** [comment]
Strange. One simple workaround would be to just hardcode the correct value for `val sparkNetHome = ...` in the relevant tests and apps.

**Comment by abongLee** [comment]
Thanks , It works . But another problem appears , 
[info] - should be fast *** FAILED ***
[info]   org.scalatest.exceptions.TestFailedException was thrown. (PreprocessorSpec.scala:146)
I check the 146 line of PreprocessorSpec.scala is
assert(totalTime <= 0.2)
I try recomplie and things work out after comment  assert(totalTime <= 0.2)
I am not sure if there are some latent problems?

**Comment by robertnishihara** [comment]
Yeah, that line was meant to indicate that certain operations should be relatively fast, but the actual speed will depend on other factors and that line can fail even if there are no errors.

**Comment by abongLee** [comment]
Thanks, robert. It really helps
