### ISSUE TITLE
Issue regarding building SparkNet for existing Spark Cluster

### ISSUE THREAD

**Issue by prakhar21** [amplab/SparkNet#129]
Hey, I am facing problem in building SparkNet, I have followed steps written under building it for existing Spark Cluster and since I don't plan to use GPU to have skipped CUDA step (Step 1). After I run 'sbt assembly', the error thrown is 

```
[info] Run completed in 10 seconds, 779 milliseconds.
[info] Total number of tests run: 6
[info] Suites: completed 5, aborted 0
[info] Tests: succeeded 6, failed 0, canceled 0, ignored 9, pending 0
[info] All tests passed.
[error] Error during tests:
[error]     TensorFlowNetSpec
[error] (test:test) sbt.TestsFailedException: Tests unsuccessful
```

Is there any dependency that is not mentioned in the README.md ?

**Comment by robertnishihara** [comment]
The current build.sbt file in the repository pulls jars that were built with CUDA. In order to use only CPUs, change the line

``` scala
resolvers += "javacpp" at "http://www.eecs.berkeley.edu/~rkn/snapshot-2016-03-05/"
```

in `build.sbt` to use the jars that were built for CPU usage ("http://www.eecs.berkeley.edu/~rkn/snapshot-2016-03-16-CPU/").

**Comment by prakhar21** [comment]
@robertnishihara Got that working, by making changes in the build.sbt  
Thanks.

**Comment by robertnishihara** [comment]
Excellent!
