### ISSUE TITLE
Small typo in the code

### ISSUE THREAD

**Issue by jaewoosong** [amplab/SparkNet#56]
Good afternoon!
Probably `log("testing, i")` in `CifarApp.scala` (line 102) is a typo of 'log("testing", i)`?

**Comment by pcmoritz** [comment]
Good catch! Do you want to go ahead and create a pull request for the fix? It could be your first code contribution to SparkNet (simple fixes like this are a great way to start contributing to a project).

**Comment by jaewoosong** [comment]
I did. Thanks!

**Comment by pcmoritz** [comment]
Awesome, thanks! I just merged it.
