### ISSUE TITLE
java.lang.UnsatisfiedLinkError: no jniopencv_core in java.library.path

### ISSUE THREAD

**Issue by rahulbhalerao001** [amplab/SparkNet#95]
Error after pulling the new changes and building sbt assembly. Trying out this solution - https://github.com/bytedeco/javacv/issues/122

**Comment by pcmoritz** [comment]
Hey,

there are a number of reasons why you might get this error, to find out which one it is, can you please post the full error message? There is most likely another error a little further down about a .so file which probably will tell us more.

Best,
Philipp.

**Comment by rahulbhalerao001** [comment]
Oh, thank you for your response. Here is the other part of the error.

`CAUSED BY: JAVA.LANG.UNSATISFIEDLINKERROR: /TMP/JAVACPP825580627817/LIBJNIOPENCV_CORE.SO: /USR/LIB/X86_64-LINUX-GNU/LIBGOMP.SO.1: VERSION 'GOMP_4.0' NOT FOUND (REQUIRED BY /TMP/JAVACPP825580627817/LIBOPENCV_CORE.SO.3.1)`

**Comment by pcmoritz** [comment]
The problem here is that the OpenMP version on the computer is too old. Which Linux distribution are you running it on?

**Comment by rahulbhalerao001** [comment]
I am using the AMI described in the Readme. The Linux distribution is Ubuntu 14.04

**Comment by robertnishihara** [comment]
Thanks for catching that. I changed the jar files (which are currently located on my website) to test a different branch and forgot about how that might affect the master branch. The jars should probably be placed somewhere a little more permanent...

It should work now. You will need to do
`rm -r $SPARKNET_HOME/targets`
`rm -r /root/.ivy2/cache/org.bytedeco*`
`cd $SPARKNET_HOME`
`sbt assembly`

**Comment by rahulbhalerao001** [comment]
Now getting this error

`java.lang.UnsatisfiedLinkError: no jnicaffe in java.library.path`
and
`Caused by: java.lang.UnsatisfiedLinkError: /tmp/javacpp349508432995/libjnicaffe.so: libcudart.so.7.5: cannot open shared object file: No such file or directory`

**Comment by robertnishihara** [comment]
Can you do `locate libcudart.so.7.5`? You should get 
```
/usr/local/cuda-7.5/targets/x86_64-linux/lib/libcudart.so.7.5
/usr/local/cuda-7.5/targets/x86_64-linux/lib/libcudart.so.7.5.18
```

**Comment by rahulbhalerao001** [comment]
I do not get anything as an output for this command.

**Comment by robertnishihara** [comment]
Can you do `updatedb` and run it again?

**Comment by robertnishihara** [comment]
Just to be sure, are you using `ami-c573c1b6`? If you start an instance with this AMI and ssh to it, those files should be there.

**Comment by rahulbhalerao001** [comment]
root@ip-172-31-24-242:~/SparkNet# updatedb
root@ip-172-31-24-242:~/SparkNet# locate libcudart.so.7.5

No output.

Again, if this is something I can solve by trial and error, please let me know.

**Comment by rahulbhalerao001** [comment]
Oh, I think I might be using an older AMI. I guess the AMI was updates twice, because I had created a new cluster after the AMI was updated.

Ok, I will try out with the AMI, and let you know in case of any issues.

**Comment by robertnishihara** [comment]
Awesome!

**Comment by rahulbhalerao001** [comment]
`[success] Total time: 146 s, completed Feb 26, 2016 2:39:29 AM`

Sorry for the false alarm. Please feel free to close this.
I wanted to know if there is a rough timeline for when the GPU mode will be reactivated.

**Comment by pcmoritz** [comment]
TensorFlow is our main priority right now, it should work with GPUs out-of-the-box. First models for this should be working soon (say about a couple of days, maybe a week) and then we'll look into Caffe GPUs again.

**Comment by rahulbhalerao001** [comment]
Ok great, looking forward to both Tensorflow integration and Caffe GPUs. Thank you for your help.
